### ISSUE TITLE
Link parsing error 

### ISSUE THREAD

**Issue by Soreine** [GitbookIO/markup-it#97]
Failure to parse https://raw.githubusercontent.com/mozilla-neutrino/neutrino-dev/master/README.md

```
TypeError: Cannot read property 'get' of undefined
    at Object.resolveRef (/user_code/node_modules/markup-it/lib/markdown/utils.js:119:20)
    at /user_code/node_modules/markup-it/lib/markdown/inlines/link.js:131:22
    at /user_code/node_modules/markup-it/lib/models/deserializer.js:50:24
    at Deserializer.<anonymous> (/user_code/node_modules/markup-it/lib/models/rule-function.js:62:28)
    at Deserializer.exec (/user_code/node_modules/markup-it/lib/models/rule-function.js:154:25)
    at Function.exec (/user_code/node_modules/markup-it/lib/models/rule-function.js:171:57)
    at /user_code/node_modules/markup-it/lib/models/rule-function.js:100:45
    at Array.some (native)
    at /user_code/node_modules/markup-it/lib/models/rule-function.js:99:30
    at Deserializer.<anonymous> (/user_code/node_modules/markup-it/lib/models/rule-function.js:62:28)
    at Deserializer.exec (/user_code/node_modules/markup-it/lib/models/rule-function.js:154:25)
    at Function.exec (/user_code/node_modules/markup-it/lib/models/rule-function.js:171:57)
    at /user_code/node_modules/markup-it/lib/models/state.js:370:41
    at List.__iterate (/user_code/node_modules/immutable/dist/immutable.js:2206:13)
    at List.forEach (/user_code/node_modules/immutable/dist/immutable.js:4381:19)
    at State.applyRules (/user_code/node_modules/markup-it/lib/models/state.js:369:16)
    at State.lex (/user_code/node_modules/markup-it/lib/models/state.js:329:39)
    at State.deserialize (/user_code/node_modules/markup-it/lib/models/state.js:388:74)
    at /user_code/node_modules/markup-it/lib/markdown/blocks/paragraph.js:37:37
    at /user_code/node_modules/markup-it/lib/models/deserializer.js:50:24
    at Deserializer.<anonymous> (/user_code/node_modules/markup-it/lib/models/rule-function.js:62:28)
    at Deserializer.exec (/user_code/node_modules/markup-it/lib/models/rule-function.js:154:25)
    at Function.exec (/user_code/node_modules/markup-it/lib/models/rule-function.js:171:57)
    at /user_code/node_modules/markup-it/lib/models/state.js:370:41
    at List.__iterate (/user_code/node_modules/immutable/dist/immutable.js:2206:13)
    at List.forEach (/user_code/node_modules/immutable/dist/immutable.js:4381:19)
    at State.applyRules (/user_code/node_modules/markup-it/lib/models/state.js:369:16)
```

**Comment by SamyPesse** [comment]
Fixed by #98
